#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  1 19:48:55 2021

@author: ece
"""

#the program calcilate the score of pros and cons of a topic,which can be used to create the attitude bar later. The program also shows how many tweets in total has been used.

from datetime import datetime
startTime = datetime.now()
import json
import tweepy #https://github.com/tweepy/tweepy
import os
from google.cloud import language_v1



def anatweet (str):

      i=0
      j=0
      k=0
      t=''
      os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/home/ece/ec601/creds.json"
      client = language_v1.LanguageServiceClient()
      consumer_key = ""
      consumer_secret = ""
      access_key = ""
      access_secret = ""
      auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
      auth.set_access_token(access_key, access_secret)
      api = tweepy.API(auth)

      usr = api.get_user(str)
      stat = api.user_timeline(str, count=10)
      
      for n in stat:
        print(i.text, end = "\n\n")
        text = i.text
        document = language_v1.Document(content=text, type_=language_v1.Document.Type.PLAIN_TEXT)
        sentiment = client.analyze_sentiment(request={'document': document}).document_sentiment
        print("Text: {}".format(i.text))
        print("Sentiment: {}, {}".format(sentiment.score, sentiment.magnitude))
        if(sentiment.score < 0 or sentiment.magnitude < 0):
            print('Negative attitude')
        elif(sentiment.score == 0 or sentiment.magnitude == 0):
            print('Neutral attitude')
        elif(sentiment.score > 0 or sentiment.magnitude > 0):
            print('Positive attitude')
        print("Location: " + str(usr.location))
        i=i+sentiment.score
        j=j+1
        if ((sentiment.score>=0.25 or sentiment.magnitude>=0.25)&(sentiment.score<=0.75 or sentiment.magnitude<=0.75)):
                 k=k+1
                 i=i-sentiment.score
      print()
      print('run time:','{}'.format(datetime.now() - startTime))


if __name__ == "__main__":
    try:
        anatweet("@US Open Thiem")
    except tweepy.error.TweepError as e:
        print("A mistake occur, please search according to"+ str(e))
