#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  8 21:04:35 2021

@author: ece
"""

import 601projec3finalmain as 601
import os


def main():
    def a=''
    def b=0
    a=input('please insert keyword:')
    b=int(input('please insert tweet number:'))-int('0')
    601.analyze_tweets(a,b)

