#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  8 21:04:35 2021

@author: ece
"""

import 601projec3finalmain as 601
import os
import unittest

class Testaddition(unittest.TestCase):
    def test(self):
        # search tweets and show attitude
        analyze_tweets('US open Thiem',50)
        # search user and show location
        analyze_tweets('@ThiemDomi',50)
        # report when API do not support getting the amount of tweets needed 
        analyze_tweets('Nadal',200)
        # report when API unable to find enough tweet needed
        analyze_tweets('tennisAAAAA',90)
        #an error when processing
        analyze_tweets('@1',50)

class APImotivate(unittest.TestCase):

    def motivate(self):
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="  "
        CONS_KEY = " "
        CONS_SECRET = " "
        ACC_TOKEN = " "
        ACC_SECRET = " "


    
if __name__ == '__main__':
    unittest.main()
