#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  8 21:04:35 2021

@author: ece
"""

import 601projec3finalmain as 601
import os



def main():
    601.analyze_tweets('US open Thiem',50)
    601.analyze_tweets('@Thiem',50)
    601.analyze_tweets('@1',50)
